[tools]
java = "25"

[env]
FLAGGSKIPET_DB_HOST = "localhost"
FLAGGSKIPET_DB_PORT = "5432"
FLAGGSKIPET_DB_DATABASE = "flaggskipet"
FLAGGSKIPET_DB_USERNAME = "flaggskipet"

[tasks.build]
description = "Run build with gradle"
run = './gradlew build'

[tasks.dev]
description = "Run app using gradle"
depends = ["infra"]
run = './gradlew run'

[tasks.test]
description = "Run tests with gradle"
run = './gradlew test'

[tasks.lint]
description = "Run check with gradle"
run = './gradlew ktlintCheck'

[tasks.format]
description = "Run ktlintFormat with gradle"
run = './gradlew ktlintFormat'

[tasks.infra]
description = "Start local infrastructure"
run = 'docker-compose -f docker-compose.yaml up -d'

[tasks."infra:down"]
description = "Stop local infrastructure"
run = 'docker-compose -f docker-compose.yaml down'

[tasks."infra:clean"]
description = "Remove local infrastructure including volumes"
run = 'docker-compose -f docker-compose.yaml down --volumes'
