ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [ no.nav.flaggskipet.ApplicationKt.module ]
  }
}

database {
  host = ${?FLAGGSKIPET_DB_HOST}
  port = ${?FLAGGSKIPET_DB_PORT}
  name = ${?FLAGGSKIPET_DB_DATABASE}
  username = ${?FLAGGSKIPET_DB_USERNAME}
  password = ${?FLAGGSKIPET_DB_PASSWORD}
  url = "postgresql://"${database.host}":"${database.port}"/"${database.name}
  url = ${?FLAGGSKIPET_DB_URL}
}
