ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [ no.nav.flaggskipet.ApplicationKt.module ]
  }
}

database {
  host = ${?FLAGGSKIPET_DB_HOST}
  port = ${?FLAGGSKIPET_DB_PORT}
  name = ${?FLAGGSKIPET_DB_DATABASE}
  username = ${?FLAGGSKIPET_DB_USERNAME}
  password = ${?FLAGGSKIPET_DB_PASSWORD}
  url = "postgresql://"${database.host}":"${database.port}"/"${database.name}
  url = ${?FLAGGSKIPET_DB_URL}
  sslkey = ${?FLAGGSKIPET_DB_SSLKEY_PK8}
}

kafka {
  bootstrapServers = "localhost:9092"
  bootstrapServers = ${?FLAGGSKIPET_KAFKA_BOOTSTRAP_SERVERS}
  bootstrapServers = ${?KAFKA_BROKERS}

  consumers {
    sykmelding {
      topic = "teamsykmelding.syfo-sendt-sykmelding"
      topic = ${?FLAGGSKIPET_KAFKA_SYKMELDING_TOPIC}
      groupId = "flaggskipet-sykmelding-v1"
      groupId = ${?FLAGGSKIPET_KAFKA_SYKMELDING_GROUP_ID}
      autoOffsetReset = "earliest"
      autoOffsetReset = ${?FLAGGSKIPET_KAFKA_SYKMELDING_AUTO_OFFSET_RESET}
      maxPollRecords = 100
      maxPollRecords = ${?FLAGGSKIPET_KAFKA_SYKMELDING_MAX_POLL_RECORDS}
    }
  }

  truststorePath = ${?KAFKA_TRUSTSTORE_PATH}
  keystorePath = ${?KAFKA_KEYSTORE_PATH}
  credentialStorePassword = ${?KAFKA_CREDSTORE_PASSWORD}
}
