apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flaggskipet
  namespace: team-esyfo
  labels:
    team: team-esyfo
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/health/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/health/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  ingresses:
    - "https://flaggskipet.intern.dev.nav.no"
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: ereg-services
          namespace: arbeidsforhold
          cluster: dev-fss
  env:
    - name: FLAGGSKIPET_KAFKA_SYKMELDING_ENABLED
      value: "false"
    - name: EREG_API_URL
      value: "https://ereg-services-q2.intern.dev.nav.no"
  leaderElection: true
  gcp:
    sqlInstances:
      - name: flaggskipet-instance
        collation: nb_NO
        type: POSTGRES_18
        tier: db-f1-micro
        diskAutoresize: true
        databases:
          - name: flaggskipet-db
            envVarPrefix: FLAGGSKIPET_DB
